name: Print Git Remote

on:
  # Trigger the workflow on push or pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow workflow to be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  print-remote:
    runs-on: ubuntu-latest
    
    # Define environment variables at the job level from GitHub secrets
    env:
      ZENML_STORE_URL: ${{ secrets.ZENML_STORE_URL }}
      ZENML_STORE_API_KEY: ${{ secrets.ZENML_STORE_API_KEY }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ensure all history is fetched to get remote info
          fetch-depth: 0

      - name: Print Git Remote
        run: |
          echo "Configured Git Remotes:"
          git remote -v
          
          echo "\nDefault Remote URL:"
          git remote get-url origin || echo "No default remote URL found"
          
          echo "\nRemote Details:"
          git remote show origin || echo "No remote details available" 

      - name: set zenml stack
        run: |
          zenml init
          zenml stack set zenml-full-gcp-stack
          zenml integration install gcp -y
          zenml project set default
      
      - name: run simple pipeline
        run: |
          pip list
          python simple_pipeline.py